/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from '../common';

export declare namespace EventContract {
  export type CategoryInputStruct = {
    name: string;
    price: BigNumberish;
    maxSupply: BigNumberish;
    categoryURI: string;
  };

  export type CategoryInputStructOutput = [
    name: string,
    price: bigint,
    maxSupply: bigint,
    categoryURI: string,
  ] & { name: string; price: bigint; maxSupply: bigint; categoryURI: string };

  export type TicketCategoryStruct = {
    name: string;
    price: BigNumberish;
    maxSupply: BigNumberish;
    sold: BigNumberish;
    isActive: boolean;
    categoryURI: string;
  };

  export type TicketCategoryStructOutput = [
    name: string,
    price: bigint,
    maxSupply: bigint,
    sold: bigint,
    isActive: boolean,
    categoryURI: string,
  ] & {
    name: string;
    price: bigint;
    maxSupply: bigint;
    sold: bigint;
    isActive: boolean;
    categoryURI: string;
  };
}

export interface EventContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'addTicketCategories'
      | 'addTicketCategory'
      | 'categoryCount'
      | 'createdAt'
      | 'deactivateEvent'
      | 'eventDescription'
      | 'eventEndTime'
      | 'eventId'
      | 'eventStartTime'
      | 'eventTitle'
      | 'eventURI'
      | 'factory'
      | 'getAllCategories'
      | 'getCategoryURI'
      | 'getEventDetails'
      | 'getTicketCategory'
      | 'isActive'
      | 'isCategoryTicketAvailable'
      | 'isTicketAvailable'
      | 'maxTickets'
      | 'maxTicketsPerWallet'
      | 'nftContract'
      | 'organizer'
      | 'owner'
      | 'purchaseCategoryTickets'
      | 'purchaseSingleTicket'
      | 'renounceOwnership'
      | 'salesEndTime'
      | 'salesStartTime'
      | 'setNFTContract'
      | 'ticketCategories'
      | 'ticketPrice'
      | 'ticketsSold'
      | 'toggleWhitelist'
      | 'transferOwnership'
      | 'updateEventDetails'
      | 'updateSalesPeriod'
      | 'updateWhitelist'
      | 'venue'
      | 'whitelist'
      | 'whitelistEnabled',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'CategoriesAdded'
      | 'CategoryAdded'
      | 'CategoryTicketPurchased'
      | 'EventDeactivated'
      | 'EventUpdated'
      | 'OwnershipTransferred'
      | 'TicketPurchased'
      | 'WhitelistUpdated',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'addTicketCategories',
    values: [EventContract.CategoryInputStruct[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'addTicketCategory',
    values: [string, BigNumberish, BigNumberish, string],
  ): string;
  encodeFunctionData(
    functionFragment: 'categoryCount',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'createdAt', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'deactivateEvent',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'eventDescription',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'eventEndTime',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'eventId', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'eventStartTime',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'eventTitle',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'eventURI', values?: undefined): string;
  encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'getAllCategories',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getCategoryURI',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'getEventDetails',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getTicketCategory',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'isActive', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'isCategoryTicketAvailable',
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'isTicketAvailable',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'maxTickets',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'maxTicketsPerWallet',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'nftContract',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'organizer', values?: undefined): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'purchaseCategoryTickets',
    values: [AddressLike, BigNumberish[], BigNumberish[]],
  ): string;
  encodeFunctionData(
    functionFragment: 'purchaseSingleTicket',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'salesEndTime',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'salesStartTime',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setNFTContract',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'ticketCategories',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'ticketPrice',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'ticketsSold',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'toggleWhitelist',
    values: [boolean],
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'updateEventDetails',
    values: [string, string, string, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'updateSalesPeriod',
    values: [BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'updateWhitelist',
    values: [AddressLike[], boolean],
  ): string;
  encodeFunctionData(functionFragment: 'venue', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'whitelist',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'whitelistEnabled',
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: 'addTicketCategories',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'addTicketCategory',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'categoryCount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'createdAt', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'deactivateEvent',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'eventDescription',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'eventEndTime',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'eventId', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'eventStartTime',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'eventTitle', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'eventURI', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'getAllCategories',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getCategoryURI',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getEventDetails',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getTicketCategory',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'isActive', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'isCategoryTicketAvailable',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'isTicketAvailable',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'maxTickets', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'maxTicketsPerWallet',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'nftContract',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'organizer', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'purchaseCategoryTickets',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'purchaseSingleTicket',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'salesEndTime',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'salesStartTime',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setNFTContract',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'ticketCategories',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'ticketPrice',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'ticketsSold',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'toggleWhitelist',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'updateEventDetails',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'updateSalesPeriod',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'updateWhitelist',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'venue', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'whitelist', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'whitelistEnabled',
    data: BytesLike,
  ): Result;
}

export namespace CategoriesAddedEvent {
  export type InputTuple = [
    categoryIds: BigNumberish[],
    totalAdded: BigNumberish,
  ];
  export type OutputTuple = [categoryIds: bigint[], totalAdded: bigint];
  export interface OutputObject {
    categoryIds: bigint[];
    totalAdded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CategoryAddedEvent {
  export type InputTuple = [
    categoryId: BigNumberish,
    name: string,
    price: BigNumberish,
    categoryURI: string,
  ];
  export type OutputTuple = [
    categoryId: bigint,
    name: string,
    price: bigint,
    categoryURI: string,
  ];
  export interface OutputObject {
    categoryId: bigint;
    name: string;
    price: bigint;
    categoryURI: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CategoryTicketPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    categoryId: BigNumberish,
    quantity: BigNumberish,
    totalPrice: BigNumberish,
  ];
  export type OutputTuple = [
    buyer: string,
    categoryId: bigint,
    quantity: bigint,
    totalPrice: bigint,
  ];
  export interface OutputObject {
    buyer: string;
    categoryId: bigint;
    quantity: bigint;
    totalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventDeactivatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventUpdatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    quantity: BigNumberish,
    totalPrice: BigNumberish,
  ];
  export type OutputTuple = [
    buyer: string,
    quantity: bigint,
    totalPrice: bigint,
  ];
  export interface OutputObject {
    buyer: string;
    quantity: bigint;
    totalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [user: AddressLike, status: boolean];
  export type OutputTuple = [user: string, status: boolean];
  export interface OutputObject {
    user: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventContract extends BaseContract {
  connect(runner?: ContractRunner | null): EventContract;
  waitForDeployment(): Promise<this>;

  interface: EventContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  addTicketCategories: TypedContractMethod<
    [_categories: EventContract.CategoryInputStruct[]],
    [bigint[]],
    'nonpayable'
  >;

  addTicketCategory: TypedContractMethod<
    [
      _name: string,
      _price: BigNumberish,
      _maxSupply: BigNumberish,
      _categoryURI: string,
    ],
    [bigint],
    'nonpayable'
  >;

  categoryCount: TypedContractMethod<[], [bigint], 'view'>;

  createdAt: TypedContractMethod<[], [bigint], 'view'>;

  deactivateEvent: TypedContractMethod<[], [void], 'nonpayable'>;

  eventDescription: TypedContractMethod<[], [string], 'view'>;

  eventEndTime: TypedContractMethod<[], [bigint], 'view'>;

  eventId: TypedContractMethod<[], [bigint], 'view'>;

  eventStartTime: TypedContractMethod<[], [bigint], 'view'>;

  eventTitle: TypedContractMethod<[], [string], 'view'>;

  eventURI: TypedContractMethod<[], [string], 'view'>;

  factory: TypedContractMethod<[], [string], 'view'>;

  getAllCategories: TypedContractMethod<
    [],
    [EventContract.TicketCategoryStructOutput[]],
    'view'
  >;

  getCategoryURI: TypedContractMethod<
    [_categoryId: BigNumberish],
    [string],
    'view'
  >;

  getEventDetails: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        string,
      ] & {
        title: string;
        description: string;
        eventOrganizer: string;
        price: bigint;
        maxTicketsCount: bigint;
        ticketsSoldCount: bigint;
        active: boolean;
        uri: string;
        creationTime: bigint;
        startTime: bigint;
        endTime: bigint;
        eventVenue: string;
      },
    ],
    'view'
  >;

  getTicketCategory: TypedContractMethod<
    [_categoryId: BigNumberish],
    [EventContract.TicketCategoryStructOutput],
    'view'
  >;

  isActive: TypedContractMethod<[], [boolean], 'view'>;

  isCategoryTicketAvailable: TypedContractMethod<
    [categoryId: BigNumberish, quantity: BigNumberish],
    [boolean],
    'view'
  >;

  isTicketAvailable: TypedContractMethod<
    [quantity: BigNumberish],
    [boolean],
    'view'
  >;

  maxTickets: TypedContractMethod<[], [bigint], 'view'>;

  maxTicketsPerWallet: TypedContractMethod<[], [bigint], 'view'>;

  nftContract: TypedContractMethod<[], [string], 'view'>;

  organizer: TypedContractMethod<[], [string], 'view'>;

  owner: TypedContractMethod<[], [string], 'view'>;

  purchaseCategoryTickets: TypedContractMethod<
    [
      buyer: AddressLike,
      quantities: BigNumberish[],
      categoryIds: BigNumberish[],
    ],
    [void],
    'payable'
  >;

  purchaseSingleTicket: TypedContractMethod<
    [buyer: AddressLike, quantity: BigNumberish],
    [void],
    'payable'
  >;

  renounceOwnership: TypedContractMethod<[], [void], 'nonpayable'>;

  salesEndTime: TypedContractMethod<[], [bigint], 'view'>;

  salesStartTime: TypedContractMethod<[], [bigint], 'view'>;

  setNFTContract: TypedContractMethod<
    [_nftContract: AddressLike],
    [void],
    'nonpayable'
  >;

  ticketCategories: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, string] & {
        name: string;
        price: bigint;
        maxSupply: bigint;
        sold: bigint;
        isActive: boolean;
        categoryURI: string;
      },
    ],
    'view'
  >;

  ticketPrice: TypedContractMethod<[], [bigint], 'view'>;

  ticketsSold: TypedContractMethod<[], [bigint], 'view'>;

  toggleWhitelist: TypedContractMethod<
    [_enabled: boolean],
    [void],
    'nonpayable'
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    'nonpayable'
  >;

  updateEventDetails: TypedContractMethod<
    [
      _description: string,
      _eventURI: string,
      _venue: string,
      _eventStartTime: BigNumberish,
      _eventEndTime: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;

  updateSalesPeriod: TypedContractMethod<
    [_startTime: BigNumberish, _endTime: BigNumberish],
    [void],
    'nonpayable'
  >;

  updateWhitelist: TypedContractMethod<
    [_addresses: AddressLike[], _status: boolean],
    [void],
    'nonpayable'
  >;

  venue: TypedContractMethod<[], [string], 'view'>;

  whitelist: TypedContractMethod<[arg0: AddressLike], [boolean], 'view'>;

  whitelistEnabled: TypedContractMethod<[], [boolean], 'view'>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(
    nameOrSignature: 'addTicketCategories',
  ): TypedContractMethod<
    [_categories: EventContract.CategoryInputStruct[]],
    [bigint[]],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'addTicketCategory',
  ): TypedContractMethod<
    [
      _name: string,
      _price: BigNumberish,
      _maxSupply: BigNumberish,
      _categoryURI: string,
    ],
    [bigint],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'categoryCount',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'createdAt',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'deactivateEvent',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'eventDescription',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'eventEndTime',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'eventId',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'eventStartTime',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'eventTitle',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'eventURI',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'factory',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'getAllCategories',
  ): TypedContractMethod<
    [],
    [EventContract.TicketCategoryStructOutput[]],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getCategoryURI',
  ): TypedContractMethod<[_categoryId: BigNumberish], [string], 'view'>;
  getFunction(nameOrSignature: 'getEventDetails'): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        string,
      ] & {
        title: string;
        description: string;
        eventOrganizer: string;
        price: bigint;
        maxTicketsCount: bigint;
        ticketsSoldCount: bigint;
        active: boolean;
        uri: string;
        creationTime: bigint;
        startTime: bigint;
        endTime: bigint;
        eventVenue: string;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getTicketCategory',
  ): TypedContractMethod<
    [_categoryId: BigNumberish],
    [EventContract.TicketCategoryStructOutput],
    'view'
  >;
  getFunction(
    nameOrSignature: 'isActive',
  ): TypedContractMethod<[], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'isCategoryTicketAvailable',
  ): TypedContractMethod<
    [categoryId: BigNumberish, quantity: BigNumberish],
    [boolean],
    'view'
  >;
  getFunction(
    nameOrSignature: 'isTicketAvailable',
  ): TypedContractMethod<[quantity: BigNumberish], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'maxTickets',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'maxTicketsPerWallet',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'nftContract',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'organizer',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'owner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'purchaseCategoryTickets',
  ): TypedContractMethod<
    [
      buyer: AddressLike,
      quantities: BigNumberish[],
      categoryIds: BigNumberish[],
    ],
    [void],
    'payable'
  >;
  getFunction(
    nameOrSignature: 'purchaseSingleTicket',
  ): TypedContractMethod<
    [buyer: AddressLike, quantity: BigNumberish],
    [void],
    'payable'
  >;
  getFunction(
    nameOrSignature: 'renounceOwnership',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'salesEndTime',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'salesStartTime',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'setNFTContract',
  ): TypedContractMethod<[_nftContract: AddressLike], [void], 'nonpayable'>;
  getFunction(nameOrSignature: 'ticketCategories'): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean, string] & {
        name: string;
        price: bigint;
        maxSupply: bigint;
        sold: bigint;
        isActive: boolean;
        categoryURI: string;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'ticketPrice',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'ticketsSold',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'toggleWhitelist',
  ): TypedContractMethod<[_enabled: boolean], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'transferOwnership',
  ): TypedContractMethod<[newOwner: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'updateEventDetails',
  ): TypedContractMethod<
    [
      _description: string,
      _eventURI: string,
      _venue: string,
      _eventStartTime: BigNumberish,
      _eventEndTime: BigNumberish,
    ],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'updateSalesPeriod',
  ): TypedContractMethod<
    [_startTime: BigNumberish, _endTime: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'updateWhitelist',
  ): TypedContractMethod<
    [_addresses: AddressLike[], _status: boolean],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'venue',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'whitelist',
  ): TypedContractMethod<[arg0: AddressLike], [boolean], 'view'>;
  getFunction(
    nameOrSignature: 'whitelistEnabled',
  ): TypedContractMethod<[], [boolean], 'view'>;

  getEvent(
    key: 'CategoriesAdded',
  ): TypedContractEvent<
    CategoriesAddedEvent.InputTuple,
    CategoriesAddedEvent.OutputTuple,
    CategoriesAddedEvent.OutputObject
  >;
  getEvent(
    key: 'CategoryAdded',
  ): TypedContractEvent<
    CategoryAddedEvent.InputTuple,
    CategoryAddedEvent.OutputTuple,
    CategoryAddedEvent.OutputObject
  >;
  getEvent(
    key: 'CategoryTicketPurchased',
  ): TypedContractEvent<
    CategoryTicketPurchasedEvent.InputTuple,
    CategoryTicketPurchasedEvent.OutputTuple,
    CategoryTicketPurchasedEvent.OutputObject
  >;
  getEvent(
    key: 'EventDeactivated',
  ): TypedContractEvent<
    EventDeactivatedEvent.InputTuple,
    EventDeactivatedEvent.OutputTuple,
    EventDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: 'EventUpdated',
  ): TypedContractEvent<
    EventUpdatedEvent.InputTuple,
    EventUpdatedEvent.OutputTuple,
    EventUpdatedEvent.OutputObject
  >;
  getEvent(
    key: 'OwnershipTransferred',
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: 'TicketPurchased',
  ): TypedContractEvent<
    TicketPurchasedEvent.InputTuple,
    TicketPurchasedEvent.OutputTuple,
    TicketPurchasedEvent.OutputObject
  >;
  getEvent(
    key: 'WhitelistUpdated',
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    'CategoriesAdded(uint256[],uint256)': TypedContractEvent<
      CategoriesAddedEvent.InputTuple,
      CategoriesAddedEvent.OutputTuple,
      CategoriesAddedEvent.OutputObject
    >;
    CategoriesAdded: TypedContractEvent<
      CategoriesAddedEvent.InputTuple,
      CategoriesAddedEvent.OutputTuple,
      CategoriesAddedEvent.OutputObject
    >;

    'CategoryAdded(uint256,string,uint256,string)': TypedContractEvent<
      CategoryAddedEvent.InputTuple,
      CategoryAddedEvent.OutputTuple,
      CategoryAddedEvent.OutputObject
    >;
    CategoryAdded: TypedContractEvent<
      CategoryAddedEvent.InputTuple,
      CategoryAddedEvent.OutputTuple,
      CategoryAddedEvent.OutputObject
    >;

    'CategoryTicketPurchased(address,uint256,uint256,uint256)': TypedContractEvent<
      CategoryTicketPurchasedEvent.InputTuple,
      CategoryTicketPurchasedEvent.OutputTuple,
      CategoryTicketPurchasedEvent.OutputObject
    >;
    CategoryTicketPurchased: TypedContractEvent<
      CategoryTicketPurchasedEvent.InputTuple,
      CategoryTicketPurchasedEvent.OutputTuple,
      CategoryTicketPurchasedEvent.OutputObject
    >;

    'EventDeactivated()': TypedContractEvent<
      EventDeactivatedEvent.InputTuple,
      EventDeactivatedEvent.OutputTuple,
      EventDeactivatedEvent.OutputObject
    >;
    EventDeactivated: TypedContractEvent<
      EventDeactivatedEvent.InputTuple,
      EventDeactivatedEvent.OutputTuple,
      EventDeactivatedEvent.OutputObject
    >;

    'EventUpdated()': TypedContractEvent<
      EventUpdatedEvent.InputTuple,
      EventUpdatedEvent.OutputTuple,
      EventUpdatedEvent.OutputObject
    >;
    EventUpdated: TypedContractEvent<
      EventUpdatedEvent.InputTuple,
      EventUpdatedEvent.OutputTuple,
      EventUpdatedEvent.OutputObject
    >;

    'OwnershipTransferred(address,address)': TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    'TicketPurchased(address,uint256,uint256)': TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
    TicketPurchased: TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;

    'WhitelistUpdated(address,bool)': TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
