/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEventTicketNFT {
  export type TicketStruct = {
    tokenId: BigNumberish;
    originalBuyer: AddressLike;
    mintedAt: BigNumberish;
    categoryId: BigNumberish;
    isUsed: boolean;
  };

  export type TicketStructOutput = [
    tokenId: bigint,
    originalBuyer: string,
    mintedAt: bigint,
    categoryId: bigint,
    isUsed: boolean
  ] & {
    tokenId: bigint;
    originalBuyer: string;
    mintedAt: bigint;
    categoryId: bigint;
    isUsed: boolean;
  };
}

export interface IEventTicketNFTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ROYALTY_FEE"
      | "balanceOf"
      | "batchMintTickets"
      | "eventContract"
      | "getTicket"
      | "getTicketsOfOwner"
      | "isTicketUsed"
      | "mintTicket"
      | "ownerOf"
      | "purchaseTickets"
      | "royaltyInfo"
      | "tickets"
      | "tokenOfOwnerByIndex"
      | "tokenURI"
      | "totalSupply"
      | "useTicket"
      | "usedTickets"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TicketMinted" | "TicketUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ROYALTY_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMintTickets",
    values: [AddressLike, string[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "eventContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTicket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketsOfOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTicketUsed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintTicket",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "purchaseTickets",
    values: [BigNumberish[], BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "royaltyInfo",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "useTicket",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usedTickets",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ROYALTY_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchMintTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTicketsOfOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTicketUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "royaltyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useTicket", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "usedTickets",
    data: BytesLike
  ): Result;
}

export namespace TicketMintedEvent {
  export type InputTuple = [
    tokenId: BigNumberish,
    buyer: AddressLike,
    categoryId: BigNumberish
  ];
  export type OutputTuple = [
    tokenId: bigint,
    buyer: string,
    categoryId: bigint
  ];
  export interface OutputObject {
    tokenId: bigint;
    buyer: string;
    categoryId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketUsedEvent {
  export type InputTuple = [tokenId: BigNumberish];
  export type OutputTuple = [tokenId: bigint];
  export interface OutputObject {
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEventTicketNFT extends BaseContract {
  connect(runner?: ContractRunner | null): IEventTicketNFT;
  waitForDeployment(): Promise<this>;

  interface: IEventTicketNFTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ROYALTY_FEE: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  batchMintTickets: TypedContractMethod<
    [
      to: AddressLike,
      tokenURIs: string[],
      categoryIds: BigNumberish[],
      quantities: BigNumberish[]
    ],
    [bigint[]],
    "nonpayable"
  >;

  eventContract: TypedContractMethod<[], [string], "view">;

  getTicket: TypedContractMethod<
    [tokenId: BigNumberish],
    [IEventTicketNFT.TicketStructOutput],
    "view"
  >;

  getTicketsOfOwner: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

  isTicketUsed: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  mintTicket: TypedContractMethod<
    [to: AddressLike, tokenURI: string, categoryId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  ownerOf: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  purchaseTickets: TypedContractMethod<
    [
      quantities: BigNumberish[],
      categoryIds: BigNumberish[],
      tokenURIs: string[]
    ],
    [bigint[]],
    "payable"
  >;

  royaltyInfo: TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint]],
    "view"
  >;

  tickets: TypedContractMethod<
    [tokenId: BigNumberish],
    [IEventTicketNFT.TicketStructOutput],
    "view"
  >;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  tokenURI: TypedContractMethod<[tokenId: BigNumberish], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  useTicket: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  usedTickets: TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ROYALTY_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchMintTickets"
  ): TypedContractMethod<
    [
      to: AddressLike,
      tokenURIs: string[],
      categoryIds: BigNumberish[],
      quantities: BigNumberish[]
    ],
    [bigint[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eventContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTicket"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IEventTicketNFT.TicketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTicketsOfOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isTicketUsed"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "mintTicket"
  ): TypedContractMethod<
    [to: AddressLike, tokenURI: string, categoryId: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ownerOf"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseTickets"
  ): TypedContractMethod<
    [
      quantities: BigNumberish[],
      categoryIds: BigNumberish[],
      tokenURIs: string[]
    ],
    [bigint[]],
    "payable"
  >;
  getFunction(
    nameOrSignature: "royaltyInfo"
  ): TypedContractMethod<
    [tokenId: BigNumberish, salePrice: BigNumberish],
    [[string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "tickets"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [IEventTicketNFT.TicketStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenURI"
  ): TypedContractMethod<[tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "useTicket"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usedTickets"
  ): TypedContractMethod<[tokenId: BigNumberish], [boolean], "view">;

  getEvent(
    key: "TicketMinted"
  ): TypedContractEvent<
    TicketMintedEvent.InputTuple,
    TicketMintedEvent.OutputTuple,
    TicketMintedEvent.OutputObject
  >;
  getEvent(
    key: "TicketUsed"
  ): TypedContractEvent<
    TicketUsedEvent.InputTuple,
    TicketUsedEvent.OutputTuple,
    TicketUsedEvent.OutputObject
  >;

  filters: {
    "TicketMinted(uint256,address,uint256)": TypedContractEvent<
      TicketMintedEvent.InputTuple,
      TicketMintedEvent.OutputTuple,
      TicketMintedEvent.OutputObject
    >;
    TicketMinted: TypedContractEvent<
      TicketMintedEvent.InputTuple,
      TicketMintedEvent.OutputTuple,
      TicketMintedEvent.OutputObject
    >;

    "TicketUsed(uint256)": TypedContractEvent<
      TicketUsedEvent.InputTuple,
      TicketUsedEvent.OutputTuple,
      TicketUsedEvent.OutputObject
    >;
    TicketUsed: TypedContractEvent<
      TicketUsedEvent.InputTuple,
      TicketUsedEvent.OutputTuple,
      TicketUsedEvent.OutputObject
    >;
  };
}
