/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IEventContract {
  export type TicketCategoryStruct = {
    name: string;
    price: BigNumberish;
    maxSupply: BigNumberish;
    sold: BigNumberish;
    isActive: boolean;
  };

  export type TicketCategoryStructOutput = [
    name: string,
    price: bigint,
    maxSupply: bigint,
    sold: bigint,
    isActive: boolean
  ] & {
    name: string;
    price: bigint;
    maxSupply: bigint;
    sold: bigint;
    isActive: boolean;
  };
}

export interface IEventContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTicketCategory"
      | "categoryCount"
      | "createdAt"
      | "deactivateEvent"
      | "eventDescription"
      | "eventEndTime"
      | "eventStartTime"
      | "eventTitle"
      | "eventURI"
      | "getEventDetails"
      | "isActive"
      | "maxTickets"
      | "maxTicketsPerWallet"
      | "nftContract"
      | "organizer"
      | "purchaseTickets"
      | "salesEndTime"
      | "salesStartTime"
      | "setNFTContract"
      | "ticketCategories"
      | "ticketPrice"
      | "ticketsSold"
      | "toggleWhitelist"
      | "updateEventDetails"
      | "updateSalesPeriod"
      | "updateWhitelist"
      | "venue"
      | "whitelist"
      | "whitelistEnabled"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CategoryAdded"
      | "EventDeactivated"
      | "EventUpdated"
      | "TicketPurchased"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addTicketCategory",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "categoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deactivateEvent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eventDescription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eventEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eventStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eventTitle",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "eventURI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getEventDetails",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isActive", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "maxTickets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTicketsPerWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nftContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "organizer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "purchaseTickets",
    values: [AddressLike, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "salesEndTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "salesStartTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setNFTContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketCategories",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ticketPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ticketsSold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleWhitelist",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEventDetails",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSalesPeriod",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelist",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(functionFragment: "venue", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistEnabled",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "addTicketCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventDescription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eventStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "eventTitle", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eventURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isActive", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxTickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxTicketsPerWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "organizer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "purchaseTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salesEndTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "salesStartTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNFTContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketsSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEventDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSalesPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "venue", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistEnabled",
    data: BytesLike
  ): Result;
}

export namespace CategoryAddedEvent {
  export type InputTuple = [
    categoryId: BigNumberish,
    name: string,
    price: BigNumberish
  ];
  export type OutputTuple = [categoryId: bigint, name: string, price: bigint];
  export interface OutputObject {
    categoryId: bigint;
    name: string;
    price: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventDeactivatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventUpdatedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPurchasedEvent {
  export type InputTuple = [
    buyer: AddressLike,
    quantity: BigNumberish,
    totalPrice: BigNumberish
  ];
  export type OutputTuple = [
    buyer: string,
    quantity: bigint,
    totalPrice: bigint
  ];
  export interface OutputObject {
    buyer: string;
    quantity: bigint;
    totalPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [user: AddressLike, status: boolean];
  export type OutputTuple = [user: string, status: boolean];
  export interface OutputObject {
    user: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IEventContract extends BaseContract {
  connect(runner?: ContractRunner | null): IEventContract;
  waitForDeployment(): Promise<this>;

  interface: IEventContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTicketCategory: TypedContractMethod<
    [_name: string, _price: BigNumberish, _maxSupply: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  categoryCount: TypedContractMethod<[], [bigint], "view">;

  createdAt: TypedContractMethod<[], [bigint], "view">;

  deactivateEvent: TypedContractMethod<[], [void], "nonpayable">;

  eventDescription: TypedContractMethod<[], [string], "view">;

  eventEndTime: TypedContractMethod<[], [bigint], "view">;

  eventStartTime: TypedContractMethod<[], [bigint], "view">;

  eventTitle: TypedContractMethod<[], [string], "view">;

  eventURI: TypedContractMethod<[], [string], "view">;

  getEventDetails: TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        title: string;
        description: string;
        eventOrganizer: string;
        price: bigint;
        maxTicketsCount: bigint;
        ticketsSoldCount: bigint;
        active: boolean;
        uri: string;
        creationTime: bigint;
        startTime: bigint;
        endTime: bigint;
        eventVenue: string;
      }
    ],
    "view"
  >;

  isActive: TypedContractMethod<[], [boolean], "view">;

  maxTickets: TypedContractMethod<[], [bigint], "view">;

  maxTicketsPerWallet: TypedContractMethod<[], [bigint], "view">;

  nftContract: TypedContractMethod<[], [string], "view">;

  organizer: TypedContractMethod<[], [string], "view">;

  purchaseTickets: TypedContractMethod<
    [
      buyer: AddressLike,
      quantities: BigNumberish[],
      categoryIds: BigNumberish[]
    ],
    [void],
    "payable"
  >;

  salesEndTime: TypedContractMethod<[], [bigint], "view">;

  salesStartTime: TypedContractMethod<[], [bigint], "view">;

  setNFTContract: TypedContractMethod<
    [_nftContract: AddressLike],
    [void],
    "nonpayable"
  >;

  ticketCategories: TypedContractMethod<
    [categoryId: BigNumberish],
    [IEventContract.TicketCategoryStructOutput],
    "view"
  >;

  ticketPrice: TypedContractMethod<[], [bigint], "view">;

  ticketsSold: TypedContractMethod<[], [bigint], "view">;

  toggleWhitelist: TypedContractMethod<
    [_enabled: boolean],
    [void],
    "nonpayable"
  >;

  updateEventDetails: TypedContractMethod<
    [
      _description: string,
      _eventURI: string,
      _venue: string,
      _eventStartTime: BigNumberish,
      _eventEndTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  updateSalesPeriod: TypedContractMethod<
    [_startTime: BigNumberish, _endTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateWhitelist: TypedContractMethod<
    [_addresses: AddressLike[], _status: boolean],
    [void],
    "nonpayable"
  >;

  venue: TypedContractMethod<[], [string], "view">;

  whitelist: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  whitelistEnabled: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTicketCategory"
  ): TypedContractMethod<
    [_name: string, _price: BigNumberish, _maxSupply: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "categoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createdAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateEvent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "eventDescription"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eventEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "eventStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "eventTitle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eventURI"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEventDetails"
  ): TypedContractMethod<
    [],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        title: string;
        description: string;
        eventOrganizer: string;
        price: bigint;
        maxTicketsCount: bigint;
        ticketsSoldCount: bigint;
        active: boolean;
        uri: string;
        creationTime: bigint;
        startTime: bigint;
        endTime: bigint;
        eventVenue: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "maxTickets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxTicketsPerWallet"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "organizer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "purchaseTickets"
  ): TypedContractMethod<
    [
      buyer: AddressLike,
      quantities: BigNumberish[],
      categoryIds: BigNumberish[]
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "salesEndTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "salesStartTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setNFTContract"
  ): TypedContractMethod<[_nftContract: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ticketCategories"
  ): TypedContractMethod<
    [categoryId: BigNumberish],
    [IEventContract.TicketCategoryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "ticketPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ticketsSold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "toggleWhitelist"
  ): TypedContractMethod<[_enabled: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEventDetails"
  ): TypedContractMethod<
    [
      _description: string,
      _eventURI: string,
      _venue: string,
      _eventStartTime: BigNumberish,
      _eventEndTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateSalesPeriod"
  ): TypedContractMethod<
    [_startTime: BigNumberish, _endTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateWhitelist"
  ): TypedContractMethod<
    [_addresses: AddressLike[], _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "venue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "whitelistEnabled"
  ): TypedContractMethod<[], [boolean], "view">;

  getEvent(
    key: "CategoryAdded"
  ): TypedContractEvent<
    CategoryAddedEvent.InputTuple,
    CategoryAddedEvent.OutputTuple,
    CategoryAddedEvent.OutputObject
  >;
  getEvent(
    key: "EventDeactivated"
  ): TypedContractEvent<
    EventDeactivatedEvent.InputTuple,
    EventDeactivatedEvent.OutputTuple,
    EventDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "EventUpdated"
  ): TypedContractEvent<
    EventUpdatedEvent.InputTuple,
    EventUpdatedEvent.OutputTuple,
    EventUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPurchased"
  ): TypedContractEvent<
    TicketPurchasedEvent.InputTuple,
    TicketPurchasedEvent.OutputTuple,
    TicketPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "CategoryAdded(uint256,string,uint256)": TypedContractEvent<
      CategoryAddedEvent.InputTuple,
      CategoryAddedEvent.OutputTuple,
      CategoryAddedEvent.OutputObject
    >;
    CategoryAdded: TypedContractEvent<
      CategoryAddedEvent.InputTuple,
      CategoryAddedEvent.OutputTuple,
      CategoryAddedEvent.OutputObject
    >;

    "EventDeactivated()": TypedContractEvent<
      EventDeactivatedEvent.InputTuple,
      EventDeactivatedEvent.OutputTuple,
      EventDeactivatedEvent.OutputObject
    >;
    EventDeactivated: TypedContractEvent<
      EventDeactivatedEvent.InputTuple,
      EventDeactivatedEvent.OutputTuple,
      EventDeactivatedEvent.OutputObject
    >;

    "EventUpdated()": TypedContractEvent<
      EventUpdatedEvent.InputTuple,
      EventUpdatedEvent.OutputTuple,
      EventUpdatedEvent.OutputObject
    >;
    EventUpdated: TypedContractEvent<
      EventUpdatedEvent.InputTuple,
      EventUpdatedEvent.OutputTuple,
      EventUpdatedEvent.OutputObject
    >;

    "TicketPurchased(address,uint256,uint256)": TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
    TicketPurchased: TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
