/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from '../common';

export interface DeploymentExampleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'createSampleEvent'
      | 'deployFactory'
      | 'estimateGasSavings'
      | 'factory'
      | 'getFactoryInfo',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: 'EventCreated' | 'FactoryDeployed',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'createSampleEvent',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'deployFactory',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'estimateGasSavings',
    values?: undefined,
  ): string;
  encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'getFactoryInfo',
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: 'createSampleEvent',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'deployFactory',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'estimateGasSavings',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'getFactoryInfo',
    data: BytesLike,
  ): Result;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    eventContract: AddressLike,
    nftContract: AddressLike,
  ];
  export type OutputTuple = [
    eventId: bigint,
    eventContract: string,
    nftContract: string,
  ];
  export interface OutputObject {
    eventId: bigint;
    eventContract: string;
    nftContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FactoryDeployedEvent {
  export type InputTuple = [factory: AddressLike];
  export type OutputTuple = [factory: string];
  export interface OutputObject {
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DeploymentExample extends BaseContract {
  connect(runner?: ContractRunner | null): DeploymentExample;
  waitForDeployment(): Promise<this>;

  interface: DeploymentExampleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  createSampleEvent: TypedContractMethod<
    [],
    [
      [bigint, string, string] & {
        eventId: bigint;
        eventContract: string;
        nftContract: string;
      },
    ],
    'nonpayable'
  >;

  deployFactory: TypedContractMethod<
    [platformFeeRecipient: AddressLike],
    [void],
    'nonpayable'
  >;

  estimateGasSavings: TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        deploymentSavings: bigint;
        eventCreationSavings: bigint;
      },
    ],
    'view'
  >;

  factory: TypedContractMethod<[], [string], 'view'>;

  getFactoryInfo: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        factoryAddress: string;
        eventImplementation: string;
        nftImplementation: string;
        platformFee: bigint;
        eventCount: bigint;
      },
    ],
    'view'
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(nameOrSignature: 'createSampleEvent'): TypedContractMethod<
    [],
    [
      [bigint, string, string] & {
        eventId: bigint;
        eventContract: string;
        nftContract: string;
      },
    ],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'deployFactory',
  ): TypedContractMethod<
    [platformFeeRecipient: AddressLike],
    [void],
    'nonpayable'
  >;
  getFunction(nameOrSignature: 'estimateGasSavings'): TypedContractMethod<
    [],
    [
      [bigint, bigint] & {
        deploymentSavings: bigint;
        eventCreationSavings: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'factory',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'getFactoryInfo'): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        factoryAddress: string;
        eventImplementation: string;
        nftImplementation: string;
        platformFee: bigint;
        eventCount: bigint;
      },
    ],
    'view'
  >;

  getEvent(
    key: 'EventCreated',
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: 'FactoryDeployed',
  ): TypedContractEvent<
    FactoryDeployedEvent.InputTuple,
    FactoryDeployedEvent.OutputTuple,
    FactoryDeployedEvent.OutputObject
  >;

  filters: {
    'EventCreated(uint256,address,address)': TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    'FactoryDeployed(address)': TypedContractEvent<
      FactoryDeployedEvent.InputTuple,
      FactoryDeployedEvent.OutputTuple,
      FactoryDeployedEvent.OutputObject
    >;
    FactoryDeployed: TypedContractEvent<
      FactoryDeployedEvent.InputTuple,
      FactoryDeployedEvent.OutputTuple,
      FactoryDeployedEvent.OutputObject
    >;
  };
}
