/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EventFactoryLibInterface extends Interface {
  getFunction(nameOrSignature: "getEventDetailsFromContract"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getEventDetailsFromContract",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEventDetailsFromContract",
    data: BytesLike
  ): Result;
}

export interface EventFactoryLib extends BaseContract {
  connect(runner?: ContractRunner | null): EventFactoryLib;
  waitForDeployment(): Promise<this>;

  interface: EventFactoryLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEventDetailsFromContract: TypedContractMethod<
    [eventContract: AddressLike],
    [
      [string, bigint, bigint, string, bigint, bigint, string] & {
        description: string;
        ticketPrice: bigint;
        maxTickets: bigint;
        eventURI: string;
        eventStartTime: bigint;
        eventEndTime: bigint;
        venue: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEventDetailsFromContract"
  ): TypedContractMethod<
    [eventContract: AddressLike],
    [
      [string, bigint, bigint, string, bigint, bigint, string] & {
        description: string;
        ticketPrice: bigint;
        maxTickets: bigint;
        eventURI: string;
        eventStartTime: bigint;
        eventEndTime: bigint;
        venue: string;
      }
    ],
    "view"
  >;

  filters: {};
}
