/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from 'ethers';
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from '../common';

export declare namespace IEventFactory {
  export type EventInfoStruct = {
    eventContract: AddressLike;
    nftContract: AddressLike;
    organizer: AddressLike;
    title: string;
    createdAt: BigNumberish;
    isActive: boolean;
    ticketsSold: BigNumberish;
    totalRevenue: BigNumberish;
  };

  export type EventInfoStructOutput = [
    eventContract: string,
    nftContract: string,
    organizer: string,
    title: string,
    createdAt: bigint,
    isActive: boolean,
    ticketsSold: bigint,
    totalRevenue: bigint,
  ] & {
    eventContract: string;
    nftContract: string;
    organizer: string;
    title: string;
    createdAt: bigint;
    isActive: boolean;
    ticketsSold: bigint;
    totalRevenue: bigint;
  };
}

export interface EventFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | 'createEvent'
      | 'deactivateEvent'
      | 'emergencyWithdraw'
      | 'eventCounter'
      | 'eventImplementation'
      | 'events'
      | 'getActiveEvents'
      | 'getAllEventIds'
      | 'getEventDetails'
      | 'getOrganizerEventCount'
      | 'getOrganizerEvents'
      | 'nftImplementation'
      | 'organizerEventCount'
      | 'organizerEvents'
      | 'organizerEventsList'
      | 'owner'
      | 'platformFee'
      | 'platformFeeRecipient'
      | 'setPlatformFee'
      | 'setPlatformFeeRecipient'
      | 'updateEventStats'
      | 'withdrawPlatformFees',
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | 'EventCreated'
      | 'EventDeactivated'
      | 'PlatformFeeRecipientUpdated'
      | 'PlatformFeeUpdated',
  ): EventFragment;

  encodeFunctionData(
    functionFragment: 'createEvent',
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
    ],
  ): string;
  encodeFunctionData(
    functionFragment: 'deactivateEvent',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'emergencyWithdraw',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'eventCounter',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'eventImplementation',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'events',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'getActiveEvents',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getAllEventIds',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'getEventDetails',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'getOrganizerEventCount',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'getOrganizerEvents',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'nftImplementation',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'organizerEventCount',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'organizerEvents',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'organizerEventsList',
    values: [AddressLike, BigNumberish],
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'platformFee',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'platformFeeRecipient',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'setPlatformFee',
    values: [BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'setPlatformFeeRecipient',
    values: [AddressLike],
  ): string;
  encodeFunctionData(
    functionFragment: 'updateEventStats',
    values: [BigNumberish, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'withdrawPlatformFees',
    values?: undefined,
  ): string;

  decodeFunctionResult(
    functionFragment: 'createEvent',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'deactivateEvent',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'emergencyWithdraw',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'eventCounter',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'eventImplementation',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'events', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'getActiveEvents',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getAllEventIds',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getEventDetails',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getOrganizerEventCount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'getOrganizerEvents',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'nftImplementation',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'organizerEventCount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'organizerEvents',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'organizerEventsList',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'platformFee',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'platformFeeRecipient',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setPlatformFee',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'setPlatformFeeRecipient',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'updateEventStats',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'withdrawPlatformFees',
    data: BytesLike,
  ): Result;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    eventContract: AddressLike,
    nftContract: AddressLike,
    title: string,
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    eventContract: string,
    nftContract: string,
    title: string,
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    eventContract: string;
    nftContract: string;
    title: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventDeactivatedEvent {
  export type InputTuple = [eventId: BigNumberish];
  export type OutputTuple = [eventId: bigint];
  export interface OutputObject {
    eventId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeRecipientUpdatedEvent {
  export type InputTuple = [newRecipient: AddressLike];
  export type OutputTuple = [newRecipient: string];
  export interface OutputObject {
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFee: BigNumberish];
  export type OutputTuple = [newFee: bigint];
  export interface OutputObject {
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventFactory extends BaseContract {
  connect(runner?: ContractRunner | null): EventFactory;
  waitForDeployment(): Promise<this>;

  interface: EventFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>,
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent,
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent,
  ): Promise<this>;

  createEvent: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _ticketPrice: BigNumberish,
      _maxTickets: BigNumberish,
      _eventURI: string,
      _eventStartTime: BigNumberish,
      _eventEndTime: BigNumberish,
      _venue: string,
      _nftName: string,
      _nftSymbol: string,
    ],
    [
      [bigint, string, string] & {
        eventId: bigint;
        eventContract: string;
        nftContract: string;
      },
    ],
    'nonpayable'
  >;

  deactivateEvent: TypedContractMethod<
    [eventId: BigNumberish],
    [void],
    'nonpayable'
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], 'nonpayable'>;

  eventCounter: TypedContractMethod<[], [bigint], 'view'>;

  eventImplementation: TypedContractMethod<[], [string], 'view'>;

  events: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean, bigint, bigint] & {
        eventContract: string;
        nftContract: string;
        organizer: string;
        title: string;
        createdAt: bigint;
        isActive: boolean;
        ticketsSold: bigint;
        totalRevenue: bigint;
      },
    ],
    'view'
  >;

  getActiveEvents: TypedContractMethod<[], [bigint[]], 'view'>;

  getAllEventIds: TypedContractMethod<[], [bigint[]], 'view'>;

  getEventDetails: TypedContractMethod<
    [eventId: BigNumberish],
    [
      [
        IEventFactory.EventInfoStructOutput,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
      ] & {
        eventInfo: IEventFactory.EventInfoStructOutput;
        description: string;
        ticketPrice: bigint;
        maxTickets: bigint;
        eventURI: string;
        eventStartTime: bigint;
        eventEndTime: bigint;
        venue: string;
      },
    ],
    'view'
  >;

  getOrganizerEventCount: TypedContractMethod<
    [organizer: AddressLike],
    [bigint],
    'view'
  >;

  getOrganizerEvents: TypedContractMethod<
    [organizer: AddressLike],
    [bigint[]],
    'view'
  >;

  nftImplementation: TypedContractMethod<[], [string], 'view'>;

  organizerEventCount: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    'view'
  >;

  organizerEvents: TypedContractMethod<
    [organizer: AddressLike, index: BigNumberish],
    [bigint],
    'view'
  >;

  organizerEventsList: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    'view'
  >;

  owner: TypedContractMethod<[], [string], 'view'>;

  platformFee: TypedContractMethod<[], [bigint], 'view'>;

  platformFeeRecipient: TypedContractMethod<[], [string], 'view'>;

  setPlatformFee: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    'nonpayable'
  >;

  setPlatformFeeRecipient: TypedContractMethod<
    [_recipient: AddressLike],
    [void],
    'nonpayable'
  >;

  updateEventStats: TypedContractMethod<
    [eventId: BigNumberish, ticketsSold: BigNumberish, revenue: BigNumberish],
    [void],
    'nonpayable'
  >;

  withdrawPlatformFees: TypedContractMethod<[], [void], 'nonpayable'>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment,
  ): T;

  getFunction(nameOrSignature: 'createEvent'): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _ticketPrice: BigNumberish,
      _maxTickets: BigNumberish,
      _eventURI: string,
      _eventStartTime: BigNumberish,
      _eventEndTime: BigNumberish,
      _venue: string,
      _nftName: string,
      _nftSymbol: string,
    ],
    [
      [bigint, string, string] & {
        eventId: bigint;
        eventContract: string;
        nftContract: string;
      },
    ],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'deactivateEvent',
  ): TypedContractMethod<[eventId: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'emergencyWithdraw',
  ): TypedContractMethod<[], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'eventCounter',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'eventImplementation',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(nameOrSignature: 'events'): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, boolean, bigint, bigint] & {
        eventContract: string;
        nftContract: string;
        organizer: string;
        title: string;
        createdAt: bigint;
        isActive: boolean;
        ticketsSold: bigint;
        totalRevenue: bigint;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getActiveEvents',
  ): TypedContractMethod<[], [bigint[]], 'view'>;
  getFunction(
    nameOrSignature: 'getAllEventIds',
  ): TypedContractMethod<[], [bigint[]], 'view'>;
  getFunction(nameOrSignature: 'getEventDetails'): TypedContractMethod<
    [eventId: BigNumberish],
    [
      [
        IEventFactory.EventInfoStructOutput,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
      ] & {
        eventInfo: IEventFactory.EventInfoStructOutput;
        description: string;
        ticketPrice: bigint;
        maxTickets: bigint;
        eventURI: string;
        eventStartTime: bigint;
        eventEndTime: bigint;
        venue: string;
      },
    ],
    'view'
  >;
  getFunction(
    nameOrSignature: 'getOrganizerEventCount',
  ): TypedContractMethod<[organizer: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'getOrganizerEvents',
  ): TypedContractMethod<[organizer: AddressLike], [bigint[]], 'view'>;
  getFunction(
    nameOrSignature: 'nftImplementation',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'organizerEventCount',
  ): TypedContractMethod<[arg0: AddressLike], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'organizerEvents',
  ): TypedContractMethod<
    [organizer: AddressLike, index: BigNumberish],
    [bigint],
    'view'
  >;
  getFunction(
    nameOrSignature: 'organizerEventsList',
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    'view'
  >;
  getFunction(
    nameOrSignature: 'owner',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'platformFee',
  ): TypedContractMethod<[], [bigint], 'view'>;
  getFunction(
    nameOrSignature: 'platformFeeRecipient',
  ): TypedContractMethod<[], [string], 'view'>;
  getFunction(
    nameOrSignature: 'setPlatformFee',
  ): TypedContractMethod<[_fee: BigNumberish], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'setPlatformFeeRecipient',
  ): TypedContractMethod<[_recipient: AddressLike], [void], 'nonpayable'>;
  getFunction(
    nameOrSignature: 'updateEventStats',
  ): TypedContractMethod<
    [eventId: BigNumberish, ticketsSold: BigNumberish, revenue: BigNumberish],
    [void],
    'nonpayable'
  >;
  getFunction(
    nameOrSignature: 'withdrawPlatformFees',
  ): TypedContractMethod<[], [void], 'nonpayable'>;

  getEvent(
    key: 'EventCreated',
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: 'EventDeactivated',
  ): TypedContractEvent<
    EventDeactivatedEvent.InputTuple,
    EventDeactivatedEvent.OutputTuple,
    EventDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: 'PlatformFeeRecipientUpdated',
  ): TypedContractEvent<
    PlatformFeeRecipientUpdatedEvent.InputTuple,
    PlatformFeeRecipientUpdatedEvent.OutputTuple,
    PlatformFeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: 'PlatformFeeUpdated',
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;

  filters: {
    'EventCreated(uint256,address,address,address,string)': TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    'EventDeactivated(uint256)': TypedContractEvent<
      EventDeactivatedEvent.InputTuple,
      EventDeactivatedEvent.OutputTuple,
      EventDeactivatedEvent.OutputObject
    >;
    EventDeactivated: TypedContractEvent<
      EventDeactivatedEvent.InputTuple,
      EventDeactivatedEvent.OutputTuple,
      EventDeactivatedEvent.OutputObject
    >;

    'PlatformFeeRecipientUpdated(address)': TypedContractEvent<
      PlatformFeeRecipientUpdatedEvent.InputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputObject
    >;
    PlatformFeeRecipientUpdated: TypedContractEvent<
      PlatformFeeRecipientUpdatedEvent.InputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputTuple,
      PlatformFeeRecipientUpdatedEvent.OutputObject
    >;

    'PlatformFeeUpdated(uint256)': TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
  };
}
